config/routes.rb
Rails.application.routes.draw do
  devise_for :groups
  get "groups/:id" => "gifts#index", as: :index
  root to: 'top#top'
  resources :groups, only: [:index, :new, :create, :update] 
  resources :gifts, only: [:index, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :group
  

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/group.rb
class Group < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :groupname, presence: true
  validates :location, presence: true
  has_many :gifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_group!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      gifts_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:groupname, :location])
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

  def index
    @gift = Gift.new
    @gifts = Gift.all.order("id DESC")
    gift = [].take(10)
    @group = Group.all
    # @gifts = @group.gifts.includes(:group)
  end

  def create
    @gift = Gift.create(gift_params)
    respond_to do |format|
      format.html { redirect_to gifts_path }
      format.json { render json: @gift}
    end
  end

  def show
    @gift = gift.find(params[:id])
  end

  private

  def gift_params
    params.require(:gift).permit(:content, :image).merge(group_id: current_group.id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def update
    if current_group.update(group_params)
      redirect_to new__supporter__path notice: 'グループ情報を変更しました'
    else
      render :edit
    end
  end

  private

  # def group_params
  #   params.require(:group).permit(:groupname, :location, :email)
  # end

  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/gifts/_gift.html.haml
.gift{"data-gift-id": "#{gift.id}"}
  .upper-gift
    .upper-gift__group__name
      = gift.group_id
    .upper-gift__date
      = gift.created_at.strftime("%Y/%m/%d %H:%M")
  .lower-gift
    - if gift.content.present?
      %p.lower-gift__content
        = gift.content
    - if gift.image.present?
      = image_tag gift.image.url, class: 'lower-gift__image' 

app/views/gifts/index.html.haml
.gifts__wrapper
  .gifts__header
    .gifts__header__left
      支援一覧ページ
    .gifts__header__middle
      足長おじさん
    .gifts__header__right
      メニュー
  .gifts__main
    .gifts__main__box
      .gifts__main__box__1
        ほげほげ
      .gifts__main__box__2
        とどけましょう
      .gifts__main__box__3
        おかいものして
      .gifts__main__box__4
        あなたの気持ちを
  .gifts__body
    .gifts__body__upper
      .gifts__body__upper__hide
      - @gifts.each do |gift|
        .gifts__body__upper__box
          .gifts__body__upper__box__date
            = gift.created_at.strftime("%Y/%m/%d %H:%M")
          .gifts__body__upper__box__image
          - if gift.image.present?
            = image_tag gift.image.url, class: 'gifts__body__upper__box__image'
          .gifts__body__upper__box__name
            = gift.group_id
          .gifts__body__upper__box__content
            = gift.content


  .gifts__form
    .gifts__form__box
      = form_for [@gift] do |f|
        = f.text_field :content, class: 'gift__message', placeholder: '    ねがいをこめて', id: "form__box"
        = f.label :image, class: 'gift__image', id: "form__box" do
          %i.fas.fa-image
            = f.file_field :image, class: 'hidden'
        = f.submit 'おくる', class: 'gift__submit', id: "form__box"
  .gifts__footer
    .gifts__footer__box
      = link_to root_path, class: 'gifts__footer__copylight' do
        またね

app/views/gifts/show.html.haml
.giftTitle
  = @gift.image.url
.giftDate
  = @giftt.created_at.strftime("%Y/%m/%d %H:%M")
.giftAuthor
.giftText
  = simple_format @gift.content

app/views/groups/index.html.haml
.index.wrapper

  .index.header
  .index.body
    .index.body__box
      - if group_signed_in?
        .box__left
          = current_group.groupname
        = link_to "ログアウト", destroy_group_session_path, method: :delete, class: "box__right"
      - else
        = link_to new_group_registration_path, class: "box__left" do
          新規登録
        = link_to new_group_session_path, class: "box__right" do
          ログイン
  .index.footer

app/views/groups/show.html.haml
.show__wrapper
  .show__header
    お願い画面
  .show__body
    .show__body__box
      = form_for (@gift) do |f|
       = f.text_field :content, class: 'form__box__message', placeholder: ' type a message', id: "form__box"
        .form__box__mask
          = f.label :image, class: 'form__box__mask__image', id: "form__box" do
          %i.fa.fa-image
          = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__box__mask__submit', id: "form__box"
  .show__footer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SupportSpace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body

    = yield

app/views/top/top.html.haml
.top.wrapper
  .top.header
    -# = video_tag("/assets/videos/stars.mp4", autoplay: true, loop: true, muted: true, style: "width:100%;")
    .top.header__message
      あしながおじさん
    
  .top.body
    .top.body__upper
    .top.body__box
      .top.body__box__1
      .top.body__box__2
        = link_to image_tag("/assets/images/hat.png", width: '100', alt: ""), gifts_path
        億り人
      .top.body__box__3
        = link_to image_tag("/assets/images/gift.png", width: '100', alt: ""), groups_path
        願い人
      .top.body__box__4
    
  .top.footer